"""empty message

Revision ID: 0a13ab2cd2b9
Revises: f175593584f9
Create Date: 2017-04-15 11:17:52.794210

"""

# revision identifiers, used by Alembic.
revision = '0a13ab2cd2b9'
down_revision = 'f175593584f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('domain', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'domain')
    ### end Alembic commands ###
