"""empty message

Revision ID: 8191b7af218f
Revises: b02df8fb7fc5
Create Date: 2017-09-19 17:37:13.473223

"""

# revision identifiers, used by Alembic.
revision = '8191b7af218f'
down_revision = 'b02df8fb7fc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('artwork_url', sa.String(), nullable=True))
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('embeddable_by', sa.String(), nullable=True))
    op.add_column('item', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('item', sa.Column('stream_url', sa.String(), nullable=True))
    op.add_column('item', sa.Column('streamable', sa.String(), nullable=True))
    op.add_column('item', sa.Column('uri', sa.String(), nullable=True))
    op.add_column('item', sa.Column('waveform_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'waveform_url')
    op.drop_column('item', 'uri')
    op.drop_column('item', 'streamable')
    op.drop_column('item', 'stream_url')
    op.drop_column('item', 'genre')
    op.drop_column('item', 'embeddable_by')
    op.drop_column('item', 'duration')
    op.drop_column('item', 'created_at')
    op.drop_column('item', 'artwork_url')
    ### end Alembic commands ###
