"""empty message

Revision ID: ed8d323c9941
Revises: 8191b7af218f
Create Date: 2017-10-10 00:42:41.433536

"""

# revision identifiers, used by Alembic.
revision = 'ed8d323c9941'
down_revision = '8191b7af218f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('pub_date', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('r_created_utc', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'r_created_utc')
    op.drop_column('item', 'pub_date')
    ### end Alembic commands ###
